### PR TITLE
Camera as flange child

### PR DESCRIPTION
**Pull request by marrts**
This allows for motion planning with the camera as a TCP

### CODE REVIEW

**Comment by marip8** [comment]
Why did this not work prior to this change? It seems like this change shouldn't be necessary

**Comment by marrts** [comment]
The tool_flange is the manipulator tip. The tool_flange is also a child of tool0 and the camera frame is a child of tool0. So Tesseract can't find the camera frame as a valid tcp link for the manipulator group ending with the tool flange. Alternatively the manipulator group can be changed to end at tool0 and I think everything should work. This was primarily an issue when IK Fast was being used, since it was generated relative to the tool_flange, but I think just KDL is used now, so the manipulator tip shouldn't matter.

**Comment by marip8** [comment]
I see; let's close this PR in favor of changing the tip link of the KDL solver.

**Comment by gavanderhoorn** [comment]
High-level comment: `tool0` is not supposed to be a parent for any other frames. It's a *leaf frame*.

Other tool frames should be children of `flange` or a frame with a similar role.

**Comment by marip8** [comment]
There is a REP (or REP proposal) that specifies that, right? I think about 95% of the URDFs I've made or used have not followed that convention

**Comment by gavanderhoorn** [comment]
Yeah: [Coordinate Frames for Serial Industrial Manipulators](http://gavanderhoorn.github.io/rep/rep-0199.html).

Specifically: [Coordinate Frames: tool0](http://gavanderhoorn.github.io/rep/rep-0199.html#tool0) and [Application-Specific Tool Frames](http://gavanderhoorn.github.io/rep/rep-0199.html#application-specific-tool-frames).

> I think about 95% of the URDFs I've made or used have not followed that convention

well it's not an active REP, so it's really just a convention written down in some `.rst` somewhere.

**Pull request closed without merging**
